name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Get hyperd version
        id: evaluate-property
        run: |
          echo "HYPER_VERSION=$(mvn help:evaluate -Dexpression=hyperapi.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Cache hyperd
        uses: actions/cache@v3
        with:
          path: |
            target/.cache
          key: ${{ runner.os }}-hyper-${{ env.HYPER_VERSION }}
          restore-keys: |
            ${{ runner.os }}-hyper-${{ env.HYPER_VERSION }}
      - name: Maven package
        run: mvn --batch-mode --no-transfer-progress clean package --file pom.xml
