name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11, 17, 21]
    name: Build with JDK ${{ matrix.java-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Get hyperd version
        id: evaluate-property
        run: |
          mvn -v
          echo "HYPER_VERSION=$(mvn help:evaluate -Dexpression=hyperapi.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Call Hyper Download workflow
        uses: ./.github/workflows/hyper-download.yml
        with:
          hyper_version: ${{ env.HYPER_VERSION }}
          target_directory: ${{ env.CURRENT_DIR }}
        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache hyperd
        uses: actions/cache@v3
        with:
          path: |
            target/.cache
          key: ${{ runner.os }}-hyper-${{ env.HYPER_VERSION }}
          restore-keys: |
            ${{ runner.os }}-hyper-${{ env.HYPER_VERSION }}
      - name: Maven package
        run: mvn --batch-mode --no-transfer-progress clean package --file pom.xml -Dskip.hyper.download=true
