name: Build and test pull request

on:
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: './.github/workflows/reusable-build-publish.yml'
    with:
      publish: true
    secrets:
      signing_key: ${{ secrets.GPG_SIGNING_KEY }}
      signing_pass: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}

