name: Build and test pull request

on:
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: './.github/workflows/reusable-build-publish.yml'
    with:
      publish: false
