name: Build, test, and release main as snapshot

on:
  release:
    types: [ "created" ]

jobs:
  call-reusable-workflow:
    uses: './.github/workflows/reusable-build-publish.yml'
    with:
      publish: true
      version: ${{ github.event.release.tag_name }}
