name: Release to staging

on:
  release:
    types: [ "created" ]

env:
  MAVEN_ARGS: --batch-mode --no-transfer-progress -V -e -Dstyle.color=always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: ossrh
          server-username: 'MAVEN_USERNAME'
          server-password: 'MAVEN_PASSWORD'
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: 'MAVEN_GPG_PASSPHRASE'
      - name: Get hyperd version
        id: evaluate-property
        run: |
          HYPER_VERSION=$(grep "<hyperapi.version>" pom.xml | sed -n 's/.*<hyperapi.version>\(.*\)<\/hyperapi.version>.*/\1/p')
          echo "HYPER_VERSION=$HYPER_VERSION" >> $GITHUB_ENV
      - name: Cache hyperd
        uses: actions/cache@v3
        with:
          path: |
            build/hyper-*.zip
          key: ${{ runner.os }}-hyper-${{ env.HYPER_VERSION }}
          restore-keys: |
            ${{ runner.os }}-hyper-${{ env.HYPER_VERSION }}
      - name: Set version
        run: mvn $MAVEN_ARGS versions:set -DnewVersion=${{ github.event.release.tag_name }}
      - name: Deploy with Maven
        run: mvn $MAVEN_ARGS clean deploy -Prelease --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}