name: Build, test, and release tag

on:
  release:
    types: [ "created" ]

jobs:
  call-reusable-workflow:
    uses: './.github/workflows/reusable-build-publish.yml'
    with:
      publish: true
      version: ${{ github.event.release.tag_name }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      signing_key: ${{ secrets.GPG_SIGNING_KEY }}
      signing_pub: ${{ secrets.GPG_SIGNING_PUBLIC_KEY }}
      signing_pass: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
      publish_user: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
      publish_pass: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
      DATACLOUD_USERNAME: ${{ secrets.DATACLOUD_USERNAME }}
      DATACLOUD_PASSWORD: ${{ secrets.DATACLOUD_PASSWORD }}
      DATACLOUD_CLIENT_ID: ${{ secrets.DATACLOUD_CLIENT_ID }}
      DATACLOUD_CLIENT_SECRET: ${{ secrets.DATACLOUD_CLIENT_SECRET }}

