name: Reusable Build and Publish

env:
  GRADLE_VERSION: "8.14"

on:
  workflow_call:
    inputs:
      publish:
        required: true
        type: boolean
        description: 'Whether to publish or not'
      version:
        required: false
        type: string
        description: 'Version to publish (tag name or snapshot)'
        default: ''
    secrets:
      signing_pass:
        required: false
      signing_key:
        required: false
      publish_user:
        required: false
      publish_pass:
        required: false
      signing_pub:
        required: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      hyper_version: ${{ steps.get_version.outputs.hyper_version }}
      resolved_version: ${{ steps.get_version.outputs.resolved_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Get hyperd version and resolved version
        id: get_version
        run: |
          HYPER_VERSION=$(gradle -q printHyperApiVersion)
          echo "hyper_version=$HYPER_VERSION" >> $GITHUB_OUTPUT
        env:
          RELEASE_VERSION: ${{ inputs.version }}

  build:
    needs: prepare
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - run: git fetch --no-tags --depth=1 origin main
      - name: Setup Java with 8 and 17 toolchains
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Cache hyper artifacts
        uses: actions/cache@v4
        with:
          path: |
            .hyper/hyper-*.zip
            .hyperd/
          key: ${{ runner.os }}-hyper-${{ needs.prepare.outputs.hyper_version }}
          restore-keys: ${{ runner.os }}-hyper-${{ needs.prepare.outputs.hyper_version }}
      - name: Extract Hyper
        id: extract_hyper
        run: gradle extractHyper
      - name: Gradle build (with version)
        id: build-and-test
        run: |
          echo "build and test with version='${{ inputs.version }}'"
          gradle clean build --no-build-cache --rerun-tasks
        env:
          RELEASE_VERSION: ${{ inputs.version }}
      - name: Generate coverage report
        run: gradle testCodeCoverageReport
        env:
          RELEASE_VERSION: ${{ inputs.version }}
      - name: Generate JaCoCo Badge (Linux only)
        if: matrix.os == 'ubuntu-latest'
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.csv
          badges-directory: .github/badges
          generate-coverage-badge: true
          generate-branches-badge: true
          generate-summary: true
          generate-coverage-endpoint: true
          generate-branches-endpoint: true
          fail-if-coverage-less-than: 60
          fail-on-coverage-decrease: true
          coverage-decrease-limit: 5
          generate-workflow-summary: true
      - name: Look at files in verification
        if: ${{ failure() }}
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: .
          exclude: ".gradle|build|bin|.git"
          depth: 3
      - name: Upload hyper logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: |
            build/hyperd/*.log
          retention-days: 5

  publish:
    needs: [ prepare, build ]
    if: ${{ inputs.publish }}
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - run: git fetch --no-tags --depth=1 origin main
      - name: Setup Java with 8 and 17 toolchains
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Double check jars
        run: gradle :verification:check -x :jdbc:test -x :jdbc-core:test -x :jdbc-http:test -x :jdbc-util:test -x :spark-datasource:test --no-build-cache --scan
      - name: Get version for jreleaser
        id: resolve_version
        run: |
          RESOLVED_VERSION=$(gradle -q printVersion)
          echo "resolved_version=$RESOLVED_VERSION" >> $GITHUB_OUTPUT
      - name: Publish to Maven Central
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{ steps.resolve_version.outputs.resolved_version }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.publish_user }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.publish_pass }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.signing_key }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.signing_pass }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_SKIP_TAG: true
      - name: Upload JReleaser logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-logs
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
          retention-days: 5
