name: Reusable Build and Publish

on:
  workflow_call:
    inputs:
      publish:
        required: true
        type: boolean
        description: 'Whether to publish or not'
      version:
        required: false
        type: string
        description: 'Version to publish (tag name or snapshot)'
        default: ''

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java with 8 and 17 toolchains
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            17
      - name: Get hyperd version
        run: |
          HYPER_VERSION=$(sed -n 's/^hyperApiVersion=\(.*\)/\1/p' gradle.properties)
          echo "HYPER_VERSION=$HYPER_VERSION" >> $GITHUB_ENV
      - name: Cache hyperd zip
        uses: actions/cache@v3
        with:
          path: build/hyper-${{ env.HYPER_VERSION }}.zip
          key: ${{ runner.os }}-hyper-${{ env.HYPER_VERSION }}
          restore-keys: ${{ runner.os }}-hyper-${{ env.HYPER_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Gradle build
        id: build
        run: ./gradlew clean build
      - name: Publish on release
        id: publish
        if: ${{ inputs.publish && (success() || steps.build.outcome == 'success') }}
        run: ./gradlew publishAllPublicationsToMavenCentralRepository --stacktrace
        env:
          RELEASE_VERSION: ${{ inputs.version }}
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          # https://docs.gradle.org/current/userguide/signing_plugin.html#sec:in-memory-keys
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
      - name: Upload hyper logs on failure
        if: ${{ failure() || steps.build.outcome == 'failure' || steps.publish.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/build/reports/
            build/hyperd/*.log
          retention-days: 5