name: Build, test, and publish main as snapshot

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: './.github/workflows/reusable-build-publish.yml'
    with:
      publish: true
